# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: UseDotNet@2
  displayName: Use .NET Core SDK 2.1.505
  inputs:
    packageType: 'sdk'
    version: '2.1.505'

- task: Npm@1
  displayName: Run npm install
  inputs:
    command: 'install'
    verbose: false

- task: CmdLine@2
  displayName: Compile SASS assets
  inputs:
    script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'

- task: Gulp@1
  displayName: Enable Code Coverage
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 
    enableCodeCoverage: false

- task: Bash@3
  displayName: Write Build files
  inputs:
    targetType: 'inline'
    script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'

- task: DotNetCoreCLI@2
  displayName: Restore project dependencies
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration Release'

